[project]
name = "http_app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "keanutoofa", email = "keanu.toofa@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "pathlib>=1.0.1",
]

[project.scripts]
http = "http_app:main"
server1 = "http_app.server1_static:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"
